"use client"
import Header from './Components/widgets/Header'
import './globals.css'
import { useEffect } from 'react'
import { initHotjar } from "./Components/Hotjar"

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  useEffect(() => {
    initHotjar();
  }, []);
  
  return (
    <html lang="en">
      <body>
        
      <Header/>
        {children}
      </body>
    </html>
  )
}
