export const  awsRegions = {
    "Afghanistan": "ap-south-1",
    "Albania": "eu-central-1",
    "Algeria": "eu-west-1",
    "Andorra": "eu-west-1",
    "Angola": "eu-central-1",
    "Antigua and Barbuda": "us-east-1",
    "Argentina": "sa-east-1",
    "Armenia": "eu-west-1",
    "Australia": "ap-southeast-2",
    "Austria": "eu-central-1",
    "Azerbaijan": "eu-central-1",
    "Bahamas": "us-east-1",
    "Bahrain": "me-south-1",
    "Bangladesh": "ap-south-1",
    "Barbados": "us-east-1",
    "Belarus": "eu-north-1",
    "Belgium": "eu-west-1",
    "Belize": "us-east-1",
    "Benin": "eu-west-1",
    "Bhutan": "ap-south-1",
    "Bolivia": "sa-east-1",
    "Bosnia and Herzegovina": "eu-central-1",
    "Botswana": "eu-west-1",
    "Brazil": "sa-east-1",
    "Brunei": "ap-southeast-1",
    "Bulgaria": "eu-central-1",
    "Burkina Faso": "eu-west-1",
    "Burundi": "eu-central-1",
    "Cabo Verde": "eu-west-1",
    "Cambodia": "ap-southeast-1",
    "Cameroon": "eu-west-1",
    "Canada": "ca-central-1",
    "Central African Republic": "eu-west-1",
    "Chad": "eu-west-1",
    "Chile": "sa-east-1",
    "China": "cn-north-1",
    "Colombia": "sa-east-1",
    "Comoros": "eu-west-1",
    "Congo": "eu-central-1",
    "Costa Rica": "us-east-1",
    "Croatia": "eu-central-1",
    "Cuba": "us-east-1",
    "Cyprus": "eu-west-1",
    "Czech Republic": "eu-central-1",
    "Democratic Republic of the Congo": "eu-central-1",
    "Denmark": "eu-west-1",
    "Djibouti": "eu-west-1",
    "Dominica": "us-east-1",
    "Dominican Republic": "us-east-1",
    "East Timor": "ap-southeast-1",
    "Ecuador": "sa-east-1",
    "Egypt": "eu-west-1",
    "El Salvador": "us-east-1",
    "Equatorial Guinea": "eu-west-1",
    "Eritrea": "eu-west-1",
    "Estonia": "eu-north-1",
    "Eswatini": "eu-west-1",
    "Ethiopia": "eu-west-1",
    "Fiji": "ap-southeast-2",
    "Finland": "eu-north-1",
    "France": "eu-west-1",
    "Gabon": "eu-west-1",
    "Gambia": "eu-west-1",
    "Georgia": "eu-west-1",
    "Germany": "eu-central-1",
    "Ghana": "eu-west-1",
    "Greece": "eu-west-1",
    "Grenada": "us-east-1",
    "Guatemala": "us-east-1",
    "Guinea": "eu-west-1",
    "Guinea-Bissau": "eu-west-1",
    "Guyana": "sa-east-1",
    "Haiti": "us-east-1",
    "Honduras": "us-east-1",
    "Hungary": "eu-central-1",
    "Iceland": "eu-west-1",
    "India": "ap-south-1",
    "Indonesia": "ap-southeast-1",
    "Iran": "eu-west-1",
    "Iraq": "eu-west-1",
    "Ireland": "eu-west-1",
    "Israel": "eu-west-1",
    "Italy": "eu-west-1",
    "Ivory Coast": "eu-west-1",
    "Jamaica": "us-east-1",
    "Japan": "ap-northeast-1",
    "Jordan": "eu-west-1",
    "Kazakhstan": "eu-central-1",
    "Kenya": "eu-west-1",
    "Kiribati": "ap-southeast-2",
    "Kuwait": "me-south-1",
    "Kyrgyzstan": "ap-south-1",
    "Laos": "ap-southeast-1",
    "Latvia": "eu-north-1",
    "Lebanon": "eu-west-1",
    "Lesotho": "eu-west-1",
    "Liberia": "eu-west-1",
    "Libya": "eu-west-1",
    "Liechtenstein": "eu-central-1",
    "Lithuania": "eu-north-1",
    "Luxembourg": "eu-west-1",
    "Madagascar": "eu-west-1",
    "Malawi": "eu-west-1",
    "Malaysia": "ap-southeast-1",
    "Maldives": "ap-south-1",
    "Mali": "eu-west-1",
    "Malta": "eu-west-1",
    "Marshall Islands": "ap-southeast-2",
    "Mauritania": "eu-west-1",
    "Mauritius": "eu-west-1",
    "Mexico": "us-west-2",
    "Micronesia": "ap-southeast-2",
    "Moldova": "eu-central-1",
    "Monaco": "eu-west-1",
    "Mongolia": "ap-northeast-1",
    "Montenegro": "eu-central-1",
    "Morocco": "eu-west-1",
    "Mozambique": "eu-west-1",
    "Myanmar": "ap-southeast-1",
    "Namibia": "eu-west-1",
    "Nauru": "ap-southeast-2",
    "Nepal": "ap-south-1",
    "Netherlands": "eu-west-1",
    "New Zealand": "ap-southeast-2",
    "Nicaragua": "us-east-1",
    "Niger": "eu-west-1",
    "Nigeria": "eu-west-1",
    "North Korea": "ap-northeast-1",
    "North Macedonia": "eu-central-1",
    "Norway": "eu-north-1",
    "Oman": "me-south-1",
    "Pakistan": "ap-south-1",
    "Palau": "ap-southeast-2",
    "Palestine": "eu-west-1",
    "Panama": "us-east-1",
    "Papua New Guinea": "ap-southeast-2",
    "Paraguay": "sa-east-1",
    "Peru": "sa-east-1",
    "Philippines": "ap-southeast-1",
    "Poland": "eu-central-1",
    "Portugal": "eu-west-1",
    "Qatar": "me-south-1",
    "Romania": "eu-central-1",
    "Russia": "eu-north-1",
    "Rwanda": "eu-west-1",
    "Saint Kitts and Nevis": "us-east-1",
    "Saint Lucia": "us-east-1",
    "Saint Vincent and the Grenadines": "us-east-1",
    "Samoa": "ap-southeast-2",
    "San Marino": "eu-west-1",
    "Sao Tome and Principe": "eu-west-1",
    "Saudi Arabia": "me-south-1",
    "Senegal": "eu-west-1",
    "Serbia": "eu-central-1",
    "Seychelles": "eu-west-1",
    "Sierra Leone": "eu-west-1",
    "Singapore": "ap-southeast-1",
    "Slovakia": "eu-central-1",
    "Slovenia": "eu-central-1",
    "Solomon Islands": "ap-southeast-2",
    "Somalia": "eu-west-1",
    "South Africa": "eu-west-1",
    "South Korea": "ap-northeast-2",
    "South Sudan": "eu-west-1",
    "Spain": "eu-west-1",
    "Sri Lanka": "ap-south-1",
    "Sudan": "eu-west-1",
    "Suriname": "sa-east-1",
    "Sweden": "eu-north-1",
    "Switzerland": "eu-central-1",
    "Syria": "eu-west-1",
    "Tajikistan": "ap-south-1",
    "Tanzania": "eu-west-1",
    "Thailand": "ap-southeast-1",
    "Togo": "eu-west-1",
    "Tonga": "ap-southeast-2",
    "Trinidad and Tobago": "us-east-1",
    "Tunisia": "eu-west-1",
    "Turkey": "eu-west-1",
    "Turkmenistan": "ap-south-1",
    "Tuvalu": "ap-southeast-2",
    "Uganda": "eu-west-1",
    "Ukraine": "eu-central-1",
    "United Arab Emirates": "me-south-1",
    "United Kingdom": "eu-west-2",
    "United States": "us-east-1",
    "Uruguay": "sa-east-1",
    "Uzbekistan": "ap-south-1",
    "Vanuatu": "ap-southeast-2",
    "Vatican City": "eu-west-1",
    "Venezuela": "sa-east-1",
    "Vietnam": "ap-southeast-1",
    "Yemen": "me-south-1",
    "Zambia": "eu-west-1",
    "Zimbabwe": "eu-west-1"
  };
  
  console.log(awsRegions);
  