export const  awsRegionsData = {
    
        "Afghanistan": { region: "ap-south-1", countryCode: "AF" },
        "Albania": { region: "eu-central-1", countryCode: "AL" },
        "Algeria": { region: "eu-west-1", countryCode: "DZ" },
        "Andorra": { region: "eu-west-1", countryCode: "AD" },
        "Angola": { region: "eu-central-1", countryCode: "AO" },
        "Antigua and Barbuda": { region: "us-east-1", countryCode: "AG" },
        "Argentina": { region: "sa-east-1", countryCode: "AR" },
        "Armenia": { region: "eu-west-1", countryCode: "AM" },
        "Australia": { region: "ap-southeast-2", countryCode: "AU" },
        "Austria": { region: "eu-central-1", countryCode: "AT" },
        "Azerbaijan": { region: "eu-central-1", countryCode: "AZ" },
        "Bahamas": { region: "us-east-1", countryCode: "BS" },
        "Bahrain": { region: "me-south-1", countryCode: "BH" },
        "Bangladesh": { region: "ap-south-1", countryCode: "BD" },
        "Barbados": { region: "us-east-1", countryCode: "BB" },
        "Belarus": { region: "eu-north-1", countryCode: "BY" },
        "Belgium": { region: "eu-west-1", countryCode: "BE" },
        "Belize": { region: "us-east-1", countryCode: "BZ" },
        "Benin": { region: "eu-west-1", countryCode: "BJ" },
        "Bhutan": { region: "ap-south-1", countryCode: "BT" },
        "Bolivia": { region: "sa-east-1", countryCode: "BO" },
        "Bosnia and Herzegovina": { region: "eu-central-1", countryCode: "BA" },
        "Botswana": { region: "eu-west-1", countryCode: "BW" },
        "Brazil": { region: "sa-east-1", countryCode: "BR" },
        "Brunei": { region: "ap-southeast-1", countryCode: "BN" },
        "Bulgaria": { region: "eu-central-1", countryCode: "BG" },
        "Burkina Faso": { region: "eu-west-1", countryCode: "BF" },
        "Burundi": { region: "eu-central-1", countryCode: "BI" },
        "Cabo Verde": { region: "eu-west-1", countryCode: "CV" },
        "Cambodia": { region: "ap-southeast-1", countryCode: "KH" },
        "Cameroon": { region: "eu-west-1", countryCode: "CM" },
        "Canada": { region: "ca-central-1", countryCode: "CA" },
        "Central African Republic": { region: "eu-west-1", countryCode: "CF" },
        "Chad": { region: "eu-west-1", countryCode: "TD" },
        "Chile": { region: "sa-east-1", countryCode: "CL" },
        "China": { region: "cn-north-1", countryCode: "CN" },
        "Colombia": { region: "sa-east-1", countryCode: "CO" },
        "Comoros": { region: "eu-west-1", countryCode: "KM" },
        "Congo": { region: "eu-central-1", countryCode: "CG" },
        "Costa Rica": { region: "us-east-1", countryCode: "CR" },
        "Croatia": { region: "eu-central-1", countryCode: "HR" },
        "Cuba": { region: "us-east-1", countryCode: "CU" },
        "Cyprus": { region: "eu-west-1", countryCode: "CY" },
        "Czech Republic": { region: "eu-central-1", countryCode: "CZ" },
        "Democratic Republic of the Congo": { region: "eu-central-1", countryCode: "CD" },
        "Denmark": { region: "eu-west-1", countryCode: "DK" },
        "Djibouti": { region: "eu-west-1", countryCode: "DJ" },
        "Dominica": { region: "us-east-1", countryCode: "DM" },
        "Dominican Republic": { region: "us-east-1", countryCode: "DO" },
        "East Timor": { region: "ap-southeast-1", countryCode: "TL" },
        "Ecuador": { region: "sa-east-1", countryCode: "EC" },
        "Egypt": { region: "eu-west-1", countryCode: "EG" },
        "El Salvador": { region: "us-east-1", countryCode: "SV" },
        "Equatorial Guinea": { region: "eu-west-1", countryCode: "GQ" },
        "Eritrea": { region: "eu-west-1", countryCode: "ER" },
        "Estonia": { region: "eu-north-1", countryCode: "EE" },
        "Eswatini": { region: "eu-west-1", countryCode: "SZ" },
        "Ethiopia": { region: "eu-west-1", countryCode: "ET" },
        "Fiji": { region: "ap-southeast-2", countryCode: "FJ" },
        "Finland": { region: "eu-north-1", countryCode: "FI" },
        "France": { region: "eu-west-1", countryCode: "FR" },
        "Gabon": { region: "eu-west-1", countryCode: "GA" },
        "Gambia": { region: "eu-west-1", countryCode: "GM" },
        "Georgia": { region: "eu-west-1", countryCode: "GE" },
        "Germany": { region: "eu-central-1", countryCode: "DE" },
        "Ghana": { region: "eu-west-1", countryCode: "GH" },
        "Greece": { region: "eu-west-1", countryCode: "GR" },
        "Grenada": { region: "us-east-1", countryCode: "GD" },
        "Guatemala": { region: "us-east-1", countryCode: "GT" },
        "Guinea": { region: "eu-west-1", countryCode: "GN" },
        "Guinea-Bissau": { region: "eu-west-1", countryCode: "GW" },
    
      
    }
//   console.log(awsRegions);
  